services:
  - type: web
    name: n8n
    env: docker
     url:docker.n8n.io/n8nio/n8n
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: 6543
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        value: postgres.dzugmpscnvfslqejoim
      - key: DB_POSTGRESDB_PASSWORD
        value: "*#A263865t#*"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: strongpassword
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-Atendente.onrender.com/
